---
title: "BEZIE"
author: "Inès Bézie"
format: html
---

## Question 1

```{r}
here::i_am("eval-grades.Rproj")
library(here)
grades <- read.csv(here("grades(1).csv"))
library(dplyr)
library(tidyr)
```
## Question 2

```{r}
number_grades <- nrow(grades)
```

The dataset contains `r number_grades` grades.

## Question 3

```{r}
number_students <-
  grades |>
  distinct(id) |>
  nrow()
```

The dataset contains `r number_students` students.

## Question 4

```{r}
students <-
  grades |>
  distinct(id, group)
students |>
  slice_head(n = 7) |>
  knitr::kable()
```
```{r}
library(ggplot2)
students |>
  group_by(group) |>
  summarise(N= n()) |>
  ggplot(aes(x = factor(group), y = N)) +
  geom_col()
```
## Question 6

```{r}
grades |>
  filter(course == "History of the Arcane") |>
  group_by(group) |>
  summarise(avg_grade = sum(grade)/n()) |>
  ggplot(aes(x = group, y = avg_grade)) +
  geom_col()
```
## Question 7

```{r}
grades |>
  group_by(trimester) |>
  summarise(grades_trim = n()) |>
ggplot(aes(x = trimester, y = grades_trim)) + 
  geom_col()
```
## Question 8





